# Generated by Django 5.2.1 on 2025-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_warehouse_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
    ]
