# Generated by Django 5.2.1 on 2025-05-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('order_clerk', '下单员'), ('reviewer', '审核员'), ('technician', '技术员'), ('warehouse_clerk', '出入库员'), ('workshop_tracker', '车间跟单员')], default='order_clerk', max_length=20, verbose_name='角色'),
        ),
    ]
